CREATE sequence "PERSONS_ID_SEQ";

CREATE TABLE "PERSONS" (
	"id" INT DEFAULT PERSONS_ID_SEQ.nextval NOT NULL,
	"FIRST_NAME" NVARCHAR2(255) NOT NULL,
	"MIDDLE_NAME" NVARCHAR2(255) NOT NULL,
	"LAST_NAME" NVARCHAR2(255) NOT NULL,
	"GENDER" NVARCHAR2(255) NOT NULL,
	"BIRTH_DATE" DATE NOT NULL,
	"NATIONALITY_ID" INT NOT NULL,
	"CITIZENSHIP_ID" INT NOT NULL,
	"BIRTH_CITY_ID" INT NOT NULL,
	"BIRTH_REGION_ID" INT NOT NULL,
	"BIRTH_VILLAGE" NVARCHAR2(255) NOT NULL,
	"PASSPORT_SERIES" NVARCHAR2(255) NOT NULL,
	"PASSPORT_NUMBER" LONG NOT NULL,
	"FIN" NVARCHAR2(255) NOT NULL,
	"PASSPORT_REGISTRAR_ORGAN_ID" INT NOT NULL,
	"PASSPORT_REGISTRATION_DATE" DATE NOT NULL,
	"PASSPORT_EXPIRATION_DATE" DATE NOT NULL,
	"BLOOD_GROUP" NVARCHAR2(255) NOT NULL,
	"EYE_COLOR" NVARCHAR2(255) NOT NULL,
	constraint PERSONS_PK PRIMARY KEY ("id"));


CREATE sequence "COUNTRIES_ID_SEQ";

CREATE TABLE "COUNTRIES" (
	"ID" INT DEFAULT COUNTRIES_ID_SEQ.nextval NOT NULL,
	"CODE" INT NOT NULL,
	"ISO_CODE" CHAR(2) NOT NULL,
	"ISO3_CODE" CHAR(3) NOT NULL,
	"NAME" NVARCHAR2(255) NOT NULL,
	"NATIONALITY" NVARCHAR2(255) NOT NULL,
	constraint COUNTRIES_PK PRIMARY KEY ("ID"));

CREATE sequence "CITIES_ID_SEQ";

CREATE TABLE "CITIES" (
	"ID" INT DEFAULT CITIES_ID_SEQ.nextval NOT NULL,
	"NAME" NVARCHAR2(255) NOT NULL,
	"COUNTRY_ID" INT NOT NULL,
	constraint CITIES_PK PRIMARY KEY ("ID"));

CREATE sequence "REGIONS_ID_SEQ";

CREATE TABLE "REGIONS" (
	"ID" INT DEFAULT REGIONS_ID_SEQ.nextval NOT NULL,
	"CITY_ID" INT,
	"NAME" NVARCHAR2(255) NOT NULL,
	"COUNTRY_ID" INT NOT NULL,
	constraint REGIONS_PK PRIMARY KEY ("ID"));

CREATE sequence "PASSPORT_REGISTRAR_ORGANIZATIONS_ID_SEQ";

CREATE TABLE "PASSPORT_REGISTRAR_ORGANIZATIONS" (
	"ID" INT DEFAULT PASSPORT_REGISTRAR_ORGANIZATIONS_ID_SEQ.nextval NOT NULL,
	"NAME" NVARCHAR2(255) NOT NULL,
	constraint PASSPORT_REGISTRAR_ORGANIZATIONS_PK PRIMARY KEY ("ID"));

ALTER TABLE "PERSONS" ADD CONSTRAINT "persons_fk0" FOREIGN KEY ("NATIONALITY_ID") REFERENCES "COUNTRIES"("ID");
ALTER TABLE "PERSONS" ADD CONSTRAINT "persons_fk1" FOREIGN KEY ("CITIZENSHIP_ID") REFERENCES "COUNTRIES"("ID");
ALTER TABLE "PERSONS" ADD CONSTRAINT "persons_fk2" FOREIGN KEY ("BIRTH_CITY_ID") REFERENCES "CITIES"("ID");
ALTER TABLE "PERSONS" ADD CONSTRAINT "persons_fk3" FOREIGN KEY ("BIRTH_REGION_ID") REFERENCES "REGIONS"("ID");
ALTER TABLE "PERSONS" ADD CONSTRAINT "persons_fk4" FOREIGN KEY ("PASSPORT_REGISTRAR_ORGAN_ID") REFERENCES "PASSPORT_REGISTRAR_ORGANIZATIONS"("ID");


ALTER TABLE "CITIES" ADD CONSTRAINT "CITIES_fk0" FOREIGN KEY ("COUNTRY_ID") REFERENCES "COUNTRIES"("ID");

ALTER TABLE "REGIONS" ADD CONSTRAINT "REGIONS_fk0" FOREIGN KEY ("COUNTRY_ID") REFERENCES "COUNTRIES"("ID");
